### ISSUE TITLE
Trying to run on Heroku-18 and getting  pdfseparate: error while loading shared libraries: libpng12.so.0: cannot open shared object file: No such file or directory

### ISSUE THREAD

**Issue by chavs1997** [amitree/heroku-buildpack-poppler#1]
Hello,
I'm trying to upgrade my Node.js app, currently on Heroku-16, to Heroku-18. I have the following buildpacks
![image](https://user-images.githubusercontent.com/22081111/111521828-d0614d00-8716-11eb-9f5f-fb275cf7660e.png)
and and Aptfile with:
libssl1.0.0
poppler-utils
libpng-dev
zlib1g-dev
http://mirrors.kernel.org/ubuntu/pool/main/libp/libpng/libpng12-0_1.2.54-1ubuntu1_amd64.deb

I'm still getting the libpng12 error. Any help is appreciated.

**Comment by afn** [comment]
Sorry, but this buildpack isn't under active development. You may want to fork it, update the Dockerfile to use `heroku/heroku:18` as the base image, and rebuild the deb package.

That said, you might not even need it; I think the purpose was to provide a newer version of poppler than what was available on Heroku-16.

**Comment by chavs1997** [comment]
Any idea where I can find a buildpack with a newer version of poppler?
